### ISSUE TITLE
Compile error on macOS on travis ci

### ISSUE THREAD

**Issue by JoachimHahn** [libgamera/GAMERA#8]
Hey dear Mac users,

could you have a look at the output from Travis CI, e.g.
https://travis-ci.org/JoachimHahn/GAMERA/jobs/89276594

Is there something missing?

Thanks, 
Joachim

**Comment by zblz** [comment]
It's failing because pip is trying to install python packages into the system python distribution, for which it does not have permission to change.

A common workaround for this and to better control the environment is to install and build into either a virtual environment or a conda environment. Check the `.travis.yml` of ,e.g, astropy, gammapy, naima, to see how to do this. I imagine you could also override this by running `pip` with `sudo`.

It's not failing on linux because `pip` is not being used, but it would probably fail in the same way as the osx builds.

**Comment by JoachimHahn** [comment]
Hey, thanks a lot!

For now, I just added a 'sudo' and it works. I think I will also leave it like that because I think Mac users know how to install stuff ;)

Cheers,
Joachim
